//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int Id { get; set; }
        public int ResidentId { get; set; }
        public bool OnRent { get; set; }
        public int Number { get; set; }
        public int OwnerId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Resident Resident { get; set; }
        public virtual Resident Owner { get; set; }
    }
}
