//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public string ContactNumber3 { get; set; }
        public int MembersLiving { get; set; }
        public System.DateTime LivingStart { get; set; }
        public Nullable<System.DateTime> LivingEnd { get; set; }
        public bool OnRent { get; set; }
        public bool IsDeleted { get; set; }
    }
}
